name: Alerta Push a Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -d " Nuevo push en main - Repo actualizado correctamente" https://ntfy.sh/billiem4r